services:
  app:
    build: .
    restart: unless-stopped
    expose:
      - '3000'
    networks:
      - default
      - coolify

  nginx:
    build: ./nginx
    restart: unless-stopped
    expose:
      - '80'
    depends_on:
      - app

networks:
  coolify:
    external: true
