services:
  app:
    build: .
    restart: unless-stopped
    expose:
      - '3000'
    networks:
      - default
      - p14b0g5b0bem8q55tj3pehgv

  nginx:
    build: ./nginx
    restart: unless-stopped
    expose:
      - '80'
    depends_on:
      - app

networks:
  p14b0g5b0bem8q55tj3pehgv:
    external: true
